export const LANG_ADDED = 'data/SOCKET_LANG_ADDED';

export const LANG_DELETED = 'data/SOCKET_LANG_DELETED';

export const LANG_UPDATED = 'data/SOCKET_LANG_UPDATED';

export const TAG_ADDED = 'data/SOCKET_TAG_ADDED';

export const TAG_DELETED = 'data/SOCKET_TAG_DELETED';

export const INITIAL_LANGUAGE_SET = 'data/SOCKET_INITIAL_LANGUAGE_SET';

export const FETCH_EMPTY_PENDING = 'data/FETCH_EMPTY_PENDING';
export const FETCH_EMPTY_FULFILLED = 'data/FETCH_EMPTY_FULFILLED';
export const FETCH_EMPTY_REJECTED = 'data/FETCH_EMPTY_REJECTED';

export default {
	LANG_ADDED,
	LANG_UPDATED,
	LANG_DELETED,
	TAG_ADDED,
	TAG_DELETED,
	INITIAL_LANGUAGE_SET,
	FETCH_EMPTY_PENDING,
	FETCH_EMPTY_REJECTED,
	FETCH_EMPTY_FULFILLED
};
